# Test $d

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Python
      run: |
        python3 --version
        pip3    --version

    - name: Jinja2
      run: |
        pip3 install Jinja2

    - name: pyyaml
      run: |
        pip3 install pyyaml

    - name: Run
      run: |
        python3 test.py
